import { ReactNode } from 'react';
import {
  AppBreadcrumbProps,
  AppBreadcrumbState,
  AppConfigProps,
  AppMenuItem,
  AppMenuItemProps,
  AppSubMenuProps,
  AppTopbarRef,
  Breadcrumb,
  BreadcrumbItem,
  ChatContextProps,
  LayoutConfig,
  LayoutContextProps,
  LayoutState,
  MailContextProps,
  MenuContextProps,
  MenuModel,
  MenuModelItem,
  MenuProps,
  NodeRef,
  Page,
  TaskContextProps,
} from './layout';

type ChildContainerProps = {
  children: ReactNode;
};

export type {
  AppBreadcrumbProps,
  AppBreadcrumbState,
  AppConfigProps,
  AppMailProps,
  AppMailReplyProps,
  AppMailSidebarItem,
  AppMenuItem,
  AppMenuItemProps,
  AppSubMenuProps,
  AppTopbarRef,
  Breadcrumb,
  Breadcrumb,
  BreadcrumbItem,
  ChartDataState,
  ChartOptionsState,
  ChatContextProps,
  ChildContainerProps,
  CustomEvent,
  Demo,
  LayoutConfig,
  LayoutContextProps,
  LayoutState,
  LayoutType,
  MailContextProps,
  MenuContextProps,
  MenuModel,
  MenuModelItem,
  MenuProps,
  NodeRef,
  Page,
  SortOrderType,
  TaskContextProps,
};
